eslint-config/package.json
stylelint-config/package.json
tsconfig/package.json

repository url 수정

---

.editorconfig
README.md

add editorconfig

---

.github/workflows/prettier-config-npm-publish.yml
.gitignore
.prettierrc
.prettierrc.js
eslint-config/.gitignore
prettier-config/README.md
prettier-config/index.js
prettier-config/package-lock.json
prettier-config/package.json
stylelint-config/.gitignore
tsconfig/.gitignore

prettier-config도 패키지 배포가 가능하도록 하자
prettier-config 패키지 배포를 위한 코드들 추가
루트에 .gitignore 추가
휴먼 아이

prettier-config 추가

---

tsconfig/backend-mixed.json

backend-mixed 세트로 redstone 빌드가 성공하지 못함
템플릿에 스키마 헤더를 추가함
스모크테스트

fix: missing schema declaration in tsconfig backend mixed set

---

eslint-config/package-lock.json
eslint-config/package.json
prettier-config/package-lock.json
prettier-config/package.json
tsconfig/package-lock.json
tsconfig/package.json

0.0.1 버전의 사용이 충분히 검증되었다고 생각합니다!
이 두 패키지 외 다른 패키지는 1 이상의 메이저 버전을 가지고 있습니다.
(이전 패치 https://github.com/day1co/standards/pull/21 가 병합되고 버저닝이 되지 않아 tsconfig 도 따로 버전을 올립니다.)
버전 변경

misc: update eslint/prettier config package version to major 1.0

---

tsconfig/backend-mixed.json
tsconfig/package-lock.json
tsconfig/package.json

fix: mis declaration tsconfig schema for backend mixed set

---

eslint-config/package-lock.json
eslint-config/package.json
eslint-config/vue-es.js

- 버그 수정
- 리팩토링
- `babel-eslint`가 ESM을 import하지 못함
- 겸사겸사 `eslint-plugin-vue` 버전 갱신
`babel-eslint` -> `@babel/eslint-parser`
–
- `@babel/eslint-parser`: `^7.19.1`
- `eslint-plugin-vue`: `^9.9.0`
npm link

eslint/vue: 의존성 수정

---

eslint-config/package-lock.json
eslint-config/package.json

- 리팩토링
여기도 merge하면 액션이 알아서 package.json 고쳐주는줄 알았네요 이런;
version: 1.0.1

eslint: 패키지 버전 bump

---

.github/workflows/stylelint-config-npm-publish.yml
stylelint-config/index.js
stylelint-config/package-lock.json
stylelint-config/package.json

- stylelint 버전 변경 (14.x -> 15.x)
- stylelint-config 배포를 위한 workflow생성
- https://stylelint.io/migration-guide/to-15
- stylelint 버전 변경 (14.x -> 15.x)
- 기타 디펜던시 변경

stylelint의 버전을 15로 올립니다.

---

eslint-config/common-ts.js

import 문 이후에 한줄 띄워주는 rule 추가하는 것 어떨지 제안해봅니다.

eslint: add newline after import rule

---

eslint-config/common-ts.js

console.log를 사용하지 않기 위한 rule 추가 어떤지 제안드려봅니다.
console.log가 지금 쓰이고 있는 곳들이 있긴 해서... 일단 제안만.

eslint: add no colsole rule

---

eslint-config/common-ts.js

소스코드의 마지막 라인에 new line 이 없으면 에러를 내도록 제안합니다.

eslint/feat: eol-last: error

---

eslint-config/package-lock.json
eslint-config/package.json

eol-last 설정을 배포하기 위해 버전을 올립니다.

feat: eslint-config bump to v1.0.2

---

stylelint-config/package-lock.json
stylelint-config/package.json

전
후
- stylelint-config 내부 의존성 갱신
아직 취약점 경고가 해소되지 않은것도 있습니다..
stylelint > file-entry-cache > flat-cache > rimraf > glob > minimatch
O

stylelint-config: update dependencies

---

eslint-config/package-lock.json
eslint-config/package.json

eslint-config: update dependencies

---

stylelint-config/package-lock.json
stylelint-config/package.json

workflow에서 자동 버전업 과정이 없는것을 확인하지 못해 이전 pr에서 버전 변경을 하지 않았습니다.
stlyelint-config 내부 의존성 업데이트 버전을 배포하기 위해 버전을 올립니다. (v3.0.0 -> v3.0.1)

stylelint-config: bump to v3.0.1

---

eslint-config/package-lock.json
eslint-config/package.json

workflow에서 자동 버전업 과정이 없는것을 확인하지 못해 이전 pr에서 버전 변경을 하지 않았습니다.
eslint-config 내부 의존성 업데이트 버전을 배포하기 위해 버전을 올립니다. (v1.0.2 -> v1.0.3)

eslint-config: bump to v1.0.3

---

eslint-config/common-ts.js

eslint: add import/order rule

---

tsconfig/backend-mixed.json
tsconfig/backend.json

옵션들 정렬
두개의 파일을 비교하기가 힘들다
휴먼 아이

refactor: sort options

---

.github/workflows/eslint-config-npm-publish.yml
.github/workflows/stylelint-config-npm-publish.yml
eslint-config/package-lock.json
eslint-config/package.json
prettier-config/package-lock.json
prettier-config/package.json
tsconfig/backend-mixed.json
tsconfig/backend.json
tsconfig/common.json
tsconfig/package-lock.json
tsconfig/package.json

misc: upgrade node 20

---

.github/workflows/eslint-config-npm-publish.yml
.github/workflows/prettier-config-npm-publish.yml
.github/workflows/stylelint-config-npm-publish.yml
.github/workflows/tsconfig-npm-publish.yml
stylelint-config/.github/workflows/ci.yml
stylelint-config/.github/workflows/npm-publish.yml

node lts 적용
node 16, node 18 잔존해 있는 부분 제거
setup-node@4로 통일

misc: All packages to use Node 20

---

prettier-config/README.md
prettier-config/index.js
prettier-config/package-lock.json
prettier-config/package.json

- prettier 버전 변경 (2.8.8 -> 3.1.1)
- day1co/prettier-config@1.2.0 버전이 배포되면 1.1.0을 latest로 변경할 예정입니다. (prettier-config를 사용하는 대부분의 서비스에서 대응 작업이 완료되면 latest도 변경하려 합니다..)
- config 파일에서 esm을 지원하게 되었다 하여 변경 하였습니다. (사용하는 쪽의 코드가 늘어나긴 하네요 😅)

prettier-config: v3 적용

---

prettier-config/README.md
prettier-config/index.js
prettier-config/package-lock.json
prettier-config/package.json

https://prettier.io/blog/2023/07/05/3.0.0.html#support-config-files-in-esm-13130httpsgithubcomprettierprettierpull13130-by-fiskerhttpsgithubcomfisker
esm으로 import 하기 위해서는 사용하는 쪽에서 package.json에 type: module을 정의하거나 파일 확장자가 mjs로 정의되어야 합니다.
- config export 방식 cjs로 복원

prettier: prettierrc export 형식을 esm에서 cjs로 복원합니다.

---

stylelint-config/README.md
stylelint-config/package-lock.json
stylelint-config/package.json

- prettier 3.x 적용 및 의존성 변경
- readme 변경
O

stylelint-config: prettier 3.x 적용 및 의존성 변경

---

eslint-config/README.md
eslint-config/package-lock.json
eslint-config/package.json

- prettier 3.x 적용 및 의존성 변경
- readme 변경
peerDependencies 쪽에서 취약점 경고(critical)이 있어 함께 변경 하였습니다. (babel/eslint-parser 내부 의존성 관련) 
O

eslint-config: prettier 3.x 적용 및 의존성 변경

---

prettier-config/index.js

prettier 3.x 패키지 적용 과정에 발생하는 breaking change 를 완화 합니다.
"trailingComma": "es5" 을 추가하여 기존 코드의 변경을 최소화 합니다.
https://prettier.io/blog/2023/07/05/3.0.0.html#javascript

prettier: trailingComma 옵션을 완화합니다.

---

eslint-config/package-lock.json
eslint-config/package.json

eslint-config: v1.3.1

---

stylelint-config/package-lock.json
stylelint-config/package.json

stylelint: update dependencies
